# Generated by Django 5.2.11 on 2026-03-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boneagerecord',
            name='affected_area_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boneagerecord',
            name='bone_abnormality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boneagerecord',
            name='bone_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
