# Generated by Django 5.2.11 on 2026-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_boneagerecord_affected_area_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boneagerecord',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated/'),
        ),
    ]
