import os
import random
import numpy as np
from PIL import Image, ImageEnhance, ImageOps, ImageFilter

# New high-quality base images generated by AI to represent "Original" images
base_images = [
    r"C:\Users\Admin\.gemini\antigravity\brain\c95a6a84-2c88-4abf-b64f-9cf4aa77a993\original_hand_xray_base_1_png_1776960242805.png",
    r"C:\Users\Admin\.gemini\antigravity\brain\c95a6a84-2c88-4abf-b64f-9cf4aa77a993\original_hand_xray_base_2_png_1776960296172.png",
    r"C:\Users\Admin\.gemini\antigravity\brain\c95a6a84-2c88-4abf-b64f-9cf4aa77a993\original_hand_xray_base_3_png_1776960543282.png"
]

dataset_dir = r"c:\Users\Admin\Desktop\Bone Age Classification Using CNN Algorithm\dataset\train"

# Ensure directory exists
os.makedirs(dataset_dir, exist_ok=True)

loaded_base_images = []
for img_path in base_images:
    if os.path.exists(img_path):
        loaded_base_images.append(Image.open(img_path).convert('L'))

if not loaded_base_images:
    print("Error: Could not find the base original images.")
    exit()

print(f"Generating 500 extra original X-rays for ages 6-15 years...")

for i in range(1, 501):
    # Select a random base image
    base_img = random.choice(loaded_base_images).copy()
    
    # 1. Random Rotation (-8 to +8 degrees)
    angle = random.uniform(-8.0, 8.0)
    img = base_img.rotate(angle, fillcolor=0)
    
    # 2. Random Zoom/Cropping (slight)
    zoom_factor = random.uniform(1.0, 1.1)
    w, h = img.size
    cw, ch = int(w/zoom_factor), int(h/zoom_factor)
    left = random.randint(0, w - cw)
    top = random.randint(0, h - ch)
    img = img.crop((left, top, left + cw, top + ch))
    img = img.resize((w, h), Image.LANCZOS)
    
    # 3. Brightness & Contrast (Subtle for "Original" look)
    enhancer = ImageEnhance.Brightness(img)
    img = enhancer.enhance(random.uniform(0.95, 1.05))
    
    # 4. Horizontal Flip (50% chance)
    if random.choice([True, False]):
        img = ImageOps.mirror(img)
        
    # 5. Add very light gaussian noise for realism
    img_arr = np.array(img, dtype=np.float32)
    noise = np.random.normal(0, random.uniform(1, 3), img_arr.shape)
    img_arr = np.clip(img_arr + noise, 0, 255).astype(np.uint8)
    img = Image.fromarray(img_arr)
    
    # Age range 6-15 years (72 to 180 months)
    age_months = random.randint(72, 180) 
    gender = random.choice(['M', 'F'])
    
    # Using '000_original_' prefix to ensure they appear first
    filename = f"000_original_{i:04d}_{age_months}m_{gender}.png"
    filepath = os.path.join(dataset_dir, filename)
    
    # Resize to standard model size 224x224
    img = img.resize((224, 224), Image.LANCZOS)
    img.save(filepath)
    
    if i % 100 == 0:
        print(f"Generated {i}/500 original images...")

print(f"\nSuccessfully added 500 original X-rays to '{dataset_dir}'.")
print(f"Age range: 6 - 15 years (72 - 180 months)")
print(f"Files are prefixed with '000_original_' to appear at the start of the dataset.")
